
#ifndef SDK4_BASICSETTINGS_CONTROL_H_
#define SDK4_BASICSETTINGS_CONTROL_H_

#include <SDK4/SDK4PlatformTypes.h>
#include <SDK4/SDK4AcquireTypes.h>
#include <SDK4/SDK4CommonControlTypes.h>

#ifdef __cplusplus
extern "C" {
#endif

	//IBasicSettings
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4LoadSettings(CTRL_HANDLE hCtrl,SDK4_ENUM_SETTINGS uSetting);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SaveSettings(CTRL_HANDLE hCtrl,SDK4_ENUM_SETTINGS uSetting);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetStartupSettings(CTRL_HANDLE hCtrl,SDK4_ENUM_SETTINGS uSetting);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetStartupSettings(CTRL_HANDLE hCtrl,SDK4_ENUM_SETTINGS* puSetting);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetAccessMode(CTRL_HANDLE hCtrl, SDK4_KACCESSMODE kAccessMode);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetAccessMode(CTRL_HANDLE hCtrl, SDK4_KACCESSMODE* pkAccessMode);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetOperationMode(CTRL_HANDLE hCtrl,SDK4_ENUM_OPERATIONMODE* puMode);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetErrorRegisterStatus(CTRL_HANDLE hCtrl,uint32_t* puError);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4Restart(CTRL_HANDLE hCtrl);

#ifdef __cplusplus
}
#endif

#endif
