
#ifndef SDK4_EXPOSURE_CONTROL_H_
#define SDK4_EXPOSURE_CONTROL_H_

#include <SDK4/SDK4PlatformTypes.h>
#include <SDK4/SDK4AcquireTypes.h>
#include <SDK4/SDK4CommonControlTypes.h>
#include <SDK4/SDK4FDC10Types.h>

#ifdef __cplusplus
extern "C" {
#endif

  //IExposure
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetExposureMode(CTRL_HANDLE hCtrl,SDK4_ENUM_EXPOSUREMODE uMode);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetExposureMode(CTRL_HANDLE hCtrl,SDK4_ENUM_EXPOSUREMODE* puMode);

	//H3XR not implemented
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetExposure(CTRL_HANDLE hCtrl,SDK4_KEXPOSURE kExposure);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetExposure(CTRL_HANDLE hCtrl,SDK4_KEXPOSURE* pkExposure);

	//Zelos 0-255 : 128
	//HX3R  0-100 : 30
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetAutoExposureLevel(CTRL_HANDLE hCtrl,uint32_t uLevel);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetAutoExposureLevel(CTRL_HANDLE hCtrl,uint32_t* puLevel);
  
	//H3XR not implemented
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetAET(CTRL_HANDLE hCtrl,SDK4_ENUM_AET uAet);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetAET(CTRL_HANDLE hCtrl,SDK4_ENUM_AET* puAet);

#ifdef __cplusplus
}
#endif

#endif
