
#ifndef SDK4_SIGNALANALYSIS_CONTROL_H_
#define SDK4_SIGNALANALYSIS_CONTROL_H_

#include <SDK4/SDK4PlatformTypes.h>
#include <SDK4/SDK4AcquireTypes.h>
#include <SDK4/SDK4CommonControlTypes.h>
#include <SDK4/SDK4FDC10Types.h>

#ifdef __cplusplus
extern "C" {
#endif

   //ISignalAnalysis
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetMeasureFrameShow(CTRL_HANDLE hCtrl,SDK4_ENUM_SWITCH uShow);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetMeasureFrameShow(CTRL_HANDLE hCtrl,SDK4_ENUM_SWITCH* puShow);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetMeasureFrameColor(CTRL_HANDLE hCtrl,SDK4_ENUM_MFCOLOR uColor);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetMeasureFrameColor(CTRL_HANDLE hCtrl,SDK4_ENUM_MFCOLOR* puColor);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetMeasureWindow(CTRL_HANDLE hCtrl,SDK4_ENUM_MEASUREWINDOWSELECT uSelect,SDK4_KAREA kArea);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetMeasureWindow(CTRL_HANDLE hCtrl,SDK4_ENUM_MEASUREWINDOWSELECT uSelect,SDK4_KAREA* pkArea);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetMeasureValue(CTRL_HANDLE hCtrl,SDK4_ENUM_MEASUREVALUE uSelect,uint32_t* puValue);


#ifdef __cplusplus
}
#endif

#endif
