
#ifndef SDK4_OVERLAY_CONTROL_H_
#define SDK4_OVERLAY_CONTROL_H_

#include <SDK4/SDK4PlatformTypes.h>
#include <SDK4/SDK4AcquireTypes.h>
#include <SDK4/SDK4CommonControlTypes.h>

#ifdef __cplusplus
extern "C" {
#endif

	//IOverlay
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetOverlayShow(CTRL_HANDLE hCtrl,SDK4_ENUM_OVERLAYSELECT iSelect, SDK4_ENUM_SWITCH iOnOff);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetOverlayShow(CTRL_HANDLE hCtrl, SDK4_ENUM_OVERLAYSELECT iSelect, SDK4_ENUM_SWITCH* piOnOff);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetOverlayPosition(CTRL_HANDLE hCtrl,SDK4_ENUM_OVERLAYSELECT iSelect, SDK4_KPOSITION kPosition);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetOverlayPosition(CTRL_HANDLE hCtrl,SDK4_ENUM_OVERLAYSELECT iSelect, SDK4_KPOSITION* pkPosition);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetOverlayStyle(CTRL_HANDLE hCtrl,SDK4_ENUM_OVERLAYSELECT iSelect, SDK4_KSTYLE kStyle);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetOverlayStyle(CTRL_HANDLE hCtrl,SDK4_ENUM_OVERLAYSELECT iSelect, SDK4_KSTYLE* pkStyle);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetOverlaySize(CTRL_HANDLE hCtrl,SDK4_ENUM_OVERLAYSELECT iSelect, SDK4_KOVERLAYSIZE kSize);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetOverlaySize(CTRL_HANDLE hCtrl,SDK4_ENUM_OVERLAYSELECT iSelect, SDK4_KOVERLAYSIZE* pkSize);
 
#ifdef __cplusplus
}
#endif

#endif
