
#ifndef SDK4_DIGITALENHANCEMENT_CONTROL_H_
#define SDK4_DIGITALENHANCEMENT_CONTROL_H_

#include <SDK4/SDK4PlatformTypes.h>
#include <SDK4/SDK4AcquireTypes.h>
#include <SDK4/SDK4CommonControlTypes.h>

#ifdef __cplusplus
extern "C" {
#endif

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetBrightness(CTRL_HANDLE hCtrl,uint32_t uBrightness);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetBrightness(CTRL_HANDLE hCtrl,uint32_t* puBrightness);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetContrast(CTRL_HANDLE hCtrl,uint32_t uContrast);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetContrast(CTRL_HANDLE hCtrl,uint32_t* puContrast);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetSharpness(CTRL_HANDLE hCtrl,uint32_t uSharpness);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetSharpness(CTRL_HANDLE hCtrl,uint32_t* puSharpness);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetHistogramEqualization(CTRL_HANDLE hCtrl,SDK4_ENUM_HISTOEQUAL iSelect);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetHistogramEqualization(CTRL_HANDLE hCtrl,SDK4_ENUM_HISTOEQUAL* piSelect);
 
#ifdef __cplusplus
}
#endif

#endif
