
#ifndef SDK4_COLOR_CONTROL_H_
#define SDK4_COLOR_CONTROL_H_

#include <SDK4/SDK4PlatformTypes.h>
#include <SDK4/SDK4AcquireTypes.h>
#include <SDK4/SDK4CommonControlTypes.h>

#ifdef __cplusplus
extern "C" {
#endif

  //IColor
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetColorBalance(CTRL_HANDLE hCtrl,SDK4_KRGB kRgbGain);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetColorBalance(CTRL_HANDLE hCtrl,SDK4_KRGB* pkRgbGain);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetLightSource(CTRL_HANDLE hCtrl,SDK4_ENUM_LIGHTSOURCE iSelect);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetLightSource(CTRL_HANDLE hCtrl,SDK4_ENUM_LIGHTSOURCE* piSelect);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetColorSaturation(CTRL_HANDLE hCtrl,uint32_t uSaturation);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetColorSaturation(CTRL_HANDLE hCtrl,uint32_t* puSaturation);

  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetAutoWhiteset(CTRL_HANDLE hCtrl,SDK4_ENUM_WHITESET iSelect);
  EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetAutoWhiteset(CTRL_HANDLE hCtrl,SDK4_ENUM_WHITESET* piSelect);


#ifdef __cplusplus
}
#endif

#endif
