
#ifndef SDK4_ROA_CONTROL_H_
#define SDK4_ROA_CONTROL_H_

#include <SDK4/SDK4PlatformTypes.h>
#include <SDK4/SDK4AcquireTypes.h>
#include <SDK4/SDK4CommonControlTypes.h>


#ifdef __cplusplus
extern "C" {
#endif
  
	EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetReadoutArea(CTRL_HANDLE hCtrl,SDK4_KAREA kRoa);
	EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetReadoutArea(CTRL_HANDLE hCtrl,SDK4_KAREA* pkRoa);

	EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4SetFrameMask(CTRL_HANDLE hCtrl,SDK4_KAREA kRoa);
	EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetFrameMask(CTRL_HANDLE hCtrl,SDK4_KAREA* pkRoa);

	EXTERN_C SDK4_IMPORT_EXPORT  SDK4_ERROR  SDK4_CALLTYPE SDK4GetReadoutAreaLimits(CTRL_HANDLE hCtrl,SDK4_ENUM_ROADOMAIN uSelect,SDK4_KAREA* pkRoa);

#ifdef __cplusplus
}
#endif

#endif
