#!/bin/bash

function component {
#  -h [ --help ]                         Display a help message.
#  -c [ --c_CLIENT_IP_ADDRESS ] arg    	 Client ip address, default = 192.168.100.96
#  -p [ --p_CLIENT_PORT ] arg            Client port, default = 1025
#  -s [ --s_LASE_SERVER_IP_ADDRESS ] arg Lase server ip address, default = 192.168.100.160
#  -t [ --t_LASE_SERVER_PORT ] arg       Lase server port, default = 1024
#  -o [ --outscope ] arg                 Scope for sending lase data, default = /sense/LASE2000D/1
#  -q [ --q_position ] arg               Sensor Poistion: x y z alpha beta gamma, 
#                                        default = -2822.938, 2080.804, 0, 0, 0, 29.742
  LASE_IP=192.168.100.160
  SETUP="-2904.935 2224.319 0 0 0 29.742"
  echo "starting senseLASE_2000D_226_1 FO --s ${LASE_IP} --q ${SETUP}"
  senseLASE_2000D_226 --s ${LASE_IP} --q ${SETUP}
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
