#!/bin/bash

# common parameters

function component {

    MODULE="${BIRON_icewingDir}/icewing"
    
    DC_CONTROL_OPTIONS="-rc ${VDEMO_demoRoot}/data/icewing/settingsObjectDetectionKinect"
    AR_DATA="${prefix}/share/ARToolKit/Data"
    MARKERS="${AR_DATA}/p0.patt:${AR_DATA}/p1.patt:${AR_DATA}/p2.patt:${AR_DATA}/p3.patt:${AR_DATA}/p4.patt:${AR_DATA}/p5.patt:${AR_DATA}/p6.patt:${AR_DATA}/p7.patt:${AR_DATA}/p8.patt:${AR_DATA}/p9.patt"
    
    echo "has asus: $VDEMO_has_asus"

    if $VDEMO_has_asus; then
        GRAB_OPTIONS_KINECT=""
    else
        GRAB_OPTIONS_KINECT="--playback ${VDEMO_demoRoot}/data/objects.oni"
    fi

    ${MODULE} ${DC_CONTROL_OPTIONS} \
    -l RsbChainSwitch -a RsbChainSwitch1 "-s /bebots/chainswitch -f ${VDEMO_demoRoot}/data/chainSwitchConfig.xml" \
    -l 3DKinectGrab -a 3DKinectGrab1 "--trigger trigger_kinect ${GRAB_OPTIONS_KINECT}" \
    -l 3DKinectConvert -a 3DKinectConvert1 -x \
    -l 3DPcaSegmentation -a 3DPcaSegmentation1 " -d ${VDEMO_demoRoot}/data/pca.cfg" \
    -l ARTDetector -a ARTDetector1 "-i KinectRGB -o markers -m ${MARKERS} -c ${AR_DATA}/camera_para.dat" \
    -l MarkerFilter -a MarkerFilter1 "-i pca_boxes_out -o filtered_box --magickinectfactor 0.86" \
    -l RsbXmlExport -a RsbXmlExport1 "-i filtered_box -x /bebots/shapes" \
    -l RsbXmlExport -a RsbXmlExport2 "-i markers -x /bebots/markers"
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
