#!/bin/bash

function component {
	#cd $HOME/armcalibration && ${prefix}/bin/ccaOwn -a /armserver -t /markers -n 16 -pos ccaPoses.txt
	cca-calibration-tobi --tracker-scope /tracking --armserver-scope /armserver --rsb-conf /vol/robocup/sandbox/share/cca-calibration-tobi-1.0/tobi.rsb.conf
}

function clean_component {
    true
}

function on_start {
	true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
