#!/bin/bash

function component {

    echo "has asus: $VDEMO_has_asus"

    if $VDEMO_has_asus; then
        GRAB_OPTIONS="--input Kinect"
    else
	    GRAB_OPTIONS="--simulation ${VDEMO_demoRoot}/data/objects.oni"
    fi

    ${prefix}/bin/ClaFuRemoteTool --segmentation-config ${VDEMO_demoRoot}/data/pca.cfg --scope /clafu/results --remote /clafu/server ${GRAB_OPTIONS} --segmentation-only --info
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
