#!/bin/bash

function component {
	PARAM="-f /vol/robocup/2014/etc/furism/ism_app.conf"
    ${prefix}/bin/furismApp $PARAM
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
