#!/bin/bash

function component {
  LASE_IP=192.168.100.160
  SETUP="-2822.938, 2080.804, 0, 0, 0, 29.597"
  echo "starting senseLASE_2000D_226 FU -s ${LASE_IP} -q ${SETUP}"
  senseLASE_2000D_226 -s ${LASE_IP} -q ${SETUP}
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
