#!/bin/bash

function component {
  DEVICE=/dev/ttyACM0
  SCOPE=/senseHokuyo
  echo "starting senseHokuyo -d ${DEVICE} -o ${SCOPE}"
  senseHokuyo -d ${DEVICE} -o ${SCOPE}
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
