#!/bin/bash

function component {
  echo "starting ImperX"
  export CVBDATA=/var/opt/cvb
  export GENICAM_GENTL64_PATH=/opt/cvb/drivers/genicam
  export CVGENICAM_REGISTRY=/var/opt/cvb/Registry
  export CVB=/opt/cvb
  export GENICAM_CACHE_V2_3=/var/opt/genicam-2.3/cache
  export GENICAM_ROOT_V2_3=/opt/genicam-2.3
  export GENICAM_LOG_CONFIG_V2_3=/opt/genicam-2.3/log/config-unix/DefaultLogging.properties
  export GENICAM_GENTL64_PATH=/opt/cvb/drivers/genicam
  export CVGENICAM_REGISTRY=/var/opt/cvb/Registry
  #start file for ImperX camera
  GigEVision2RSB \
  --record 0 \
  --outscope /sense/gigevision/imperx \
  --recordFilename video.avi \
  --numFrames 0 \
  --camAcquisitionFrameRateAbs 30
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
