#!/bin/bash

function component {
        dispatcher-java.sh
}

function clean_component {
    true
}

function on_start {
    echo "checking whether we need start an own dispatcher" >&2
    if dispatcherHost; then
	echo "dispatcher already running. Using that one" >&2
	exit 0
    else
	echo "start own dispatcher" >&2
    fi
#    export XCF_DebugLevel_IceLogger=DEBUG
#    export XCF_DebugLevel_SimpleDispatcherLogger=DEBUG
#    export XCF_DebugLevel_InterceptorLogger=DEBUG
#    export XCF_DebugLevel_DispatcherInterceptDistributorLogger=DEBUG

	sleep 2
}

function on_check {

    dispatcherHost | grep "Dispatcher at Host: "
    RET="$?"
    echo "check resulted in $RET"
    exit $RET
}

function on_stop {
    true
}


source "$VDEMO_root/vdemo_standard_component_suffix.sh"
