#!/bin/bash



title="rsbam_${RSBAM_MEMORY_NAME}"

function component {

    if [ -z "${ANNOTATION_FILE}" ]; then
        echo "Annotation file not defined. Use default annotations."
          ANNOTATION_FILE=${PATH_TO_ANNOTATIONS}/annotations_${MAP}.xml
    fi
    
    if [ ! -f ${ANNOTATION_FILE} ]; then
        echo "${ANNOTATION_FILE} does not exist."
    else
        if [ -n "${RSBAM_DIR_TO_INSERT}" ]; then
            echo "### Copy annotations for map: ${MAP}" 
            mkdir ${RSBAM_DIR_TO_INSERT}
            cp -vf ${ANNOTATION_FILE} ${RSBAM_DIR_TO_INSERT}/annotations.xml
        else
            echo "RSBAM_DIR_TO_INSERT not defined" 
        fi
    fi

    if [ -n "${RSBAM_DIR_TO_INSERT}" ]; then
        LOAD_OPTION="--directory ${RSBAM_DIR_TO_INSERT}"
    else
        LOAD_OPTION=""
    fi
    #${prefix}/bin/rsbam $LOAD_OPTION $RSBAM_MEMORY_NAME
    ${prefix}/opt/rsbam-server/bin/rsbam $LOAD_OPTION $RSBAM_MEMORY_NAME --debug
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
