#!/bin/bash

function component {
       asmMultiViewController ${prefix}/etc/asm_faob.conf
}

function clean_component {
    true
}

function on_start {
	true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
