#!/bin/bash

function component {
  if [  "$VDEMO_robot_config_loaded" = "TRUE" ]; then
        ${prefix}/bin/ArmControlServer -a katana -p ${prefix}/share/ArmControlServer/KatanaBasicMovements.xml -l ${prefix}/share/ArmControlServer/KatanaLogConfig.xml
  else
          ${prefix}/bin/ArmControlServer -a katanasimulator -p ${prefix}/share/ArmControlServer/KatanaBasicMovements.xml -l ${prefix}/share/ArmControlServer/KatanaLogConfig.xml
  fi        
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
