#!/bin/bash

function component {
#  -h [ --help ]                Display a help message.
#  -o [ --outscope ] arg        Scope for sending ibeo scala 1403 values
#  -s [ --s_Scala_IP ] arg      Scala ip address, default = 192.168.1.52
#  -p [ --p_TcpServerPort ] arg Server port, default = 12002
#  -q [ --q_position ] arg      Sensor Poistion: x y z alpha beta gamma, default                                = -2645.269, 1868.837, -75, 0, 0, 13.658
  IBEOSCALA_IP=192.168.100.180
  SETUP="-2645.269 1868.837 -75 0 0 13.658"
  echo "starting senseIbeoScala_1404 VorneMitte --s ${IBEOSCALA_IP} --q ${SETUP}"
  senseIbeoScala_1403 --s ${IBEOSCALA_IP} --q ${SETUP}
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
