#!/bin/bash


function component {
    PARAM="-savemode"
    ${prefix}/bin/BodyTracker $PARAM
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
