#!/bin/bash

function component {
    ${prefix}/bin/rsb-host-monitor0.11
}

function clean_component {
    true
}

function on_start {
	true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"

