#!/bin/bash

# We use only one spread, that is why we give him localhost config


function component {
  if [  "$VDEMO_robot_config_loaded" = "TRUE" ]; then
    export SPREADCONFIG_RSB="${VDEMO_demoRoot}/data/spread-localhost-rsb.conf"
    export SPREADOPTS="-n localhost"
  else
    export SPREADCONFIG_RSB="${VDEMO_demoRoot}/data/spread-localhost-rsb.conf"
    export SPREADOPTS="-n localhost"
  fi
  
  echo "starting ${prefix}/sbin/spread ${SPREADOPTS} -c ${SPREADCONFIG_RSB}"
  ${prefix}/sbin/spread ${SPREADOPTS} -c ${SPREADCONFIG_RSB}
}

function stop_component {
    # Using -r when there is no specific need for is DARK AND EVIL
    # If Spread_Port is empty /tmp/ will be erased!
    rm -f /tmp/${RSB_TRANSPORT_SPREAD_PORT:-4803}
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
