#!/bin/bash

function component {
  echo "starting MachineModel"
#  -h [ --help ]           Display a help message.
#  -o [ --outscope ] arg   Scope for sending odometry values, dafault = 
#                          "/plan/Fahrzeugdaten"
#  -c [ --offset ] arg     Offset curvature for machine, dafault = 0.0226
#  -d [ --diskretAuf ] arg Discrete resolution for roi = 0.05
  MachineModel -c -0.0045 -d 0.05
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
