#!/bin/bash

function component {
#  -h [ --help ]              Display a help message.
#  -s [ --s_TcpServerIP ] arg   Server ip address, default = 192.168.100.150
#  -p [ --p_TcpServerPort ] arg Server port, default = 12002
#  -o [ --outscope ] arg      Scope for sending sick data, default = /sense/SickLDMRS/1
#  -q [ --q_position ] arg      Sensor Poistion: x y z alpha beta gamma, default = -2819.493, 2082.838, -206.29, 0, 0, 14.597
  SICK_IP=192.168.100.152
  SETUP="5970.071 1061.521 166 0 0 -13.5"
  echo "starting senseSick_LD_MRS FR --s ${SICK_IP} --q ${SETUP}"
  senseSick_LD_MRS --s ${SICK_IP} --q ${SETUP} --o /sense/SickLDMRS/3
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
