#!/bin/bash

function component {
	
	if [ "$DEBUG_MODE" = "TRUE" ]; then
        DEBUG_FLAG="-d"
    fi

    if [  "$VDEMO_robot_config_loaded" = "TRUE" ]; then
        ${prefix}/bin/SeAM -C ${DEBUG_FLAG} -c ${prefix}/etc/SeAM/configuration_robocup2014.xml -l ${prefix}/etc/SeAM/log4j.properties
    else
        ${prefix}/bin/SeAM_planesim ${prefix}/etc/SeAM/sim/bonsai.xml
    fi   
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"