#!/bin/bash



function component {
    # common parameters
    MODULE="${BIRON_icewingDir}/icewing"
    DC_CONTROL_OPTIONS="-rc ${VDEMO_demoRoot}/data/icewing/settingsObjectDetectionKinect"
    CLASSES=""
    for ARG in `cat ${prefix}/share/objectModels/coldClasses.txt`
    do
	CLASSES="${prefix}/share/objectModels/$ARG.png;$CLASSES"
    done
    ${MODULE} ${DC_CONTROL_OPTIONS} \
	-l ${prefix}/lib/iceWing/libXcfChainSwitch.so \
	-a XcfChainSwitch1 "-s OdcChainSwitchServer -f ${VDEMO_demoRoot}/data/chainSwitchConfigKinectOdc.xml" \
	-l ${prefix}/lib/iceWing/libXCFExport.so \
	-a XCFExport1 "-x odcObject -i ColdBBoxOut" \
	-l ${prefix}/lib/iceWing/libXCFExport.so \
	-a XCFExport2 "-x odcObject3D -i CroppedXYZ" \
	-l ${prefix}/lib/iceWing/lib3DKinectGrab.so \
	-a 3DKinectGrab1 "--trigger KinectTrigger -p ${prefix}/share/objects.oni --rgb_resx 1280 --rgb_resy 1024 --rgb_fps 15 " \
	-l ${prefix}/lib/iceWing/lib3DKinectConvert.so \
	-a 3DKinectConvert1 "-i KinectDistance -x" \
	-l ${prefix}/lib/iceWing/lib3DPcaSegmentation.so \
	-a 3DPcaSegmentation1 "-i KinectXYZ -d ${VDEMO_demoRoot}/data/pca.cfg " \
	-l ${prefix}/lib/iceWing/libiw_cold_bbox.so \
	-a ColdInBBox1 "-m ${CLASSES} -i imgMasked -b CroppedXYZ"
    #-l ${prefix}/lib/iceWing/libPMKSVM.so \
	#-a PMKSVM1 "-d ${prefix}/share/objectModels -c ${prefix}/share/objectModels/clusters -i KinectRGB -b ColdBBoxOut"
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
