#!/bin/bash

function component {
    rsb-loggercpp0.11 --style monitor --scope /
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
