#!/bin/bash

#Door_detector

# common parameters

# settings files

function component {
    ${prefix}/bin/door_detector --sensor_height 1.54 -s 0.061 --rg_smooth_mode --knob_width_std 0.095 --knob_floor_dist_std 1.0 -y 0.0065 --door_height_std 1.4 --knob_frame_dist_std 0.015
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}


source "$VDEMO_root/vdemo_standard_component_suffix.sh"
