#!/bin/bash

function component {
  SICK_IP=192.168.100.150
  SETUP="-2819.493, 2082.838, -206.29, 0, 0, 14.597"
  echo "starting senseSick_LD_MRS FR -s ${SICK_IP} -q ${SETUP}"
  senseSick_LD_MRS -s ${SICK_IP} -q ${SETUP}
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
