#!/bin/bash

function component {
  SICK_IP=192.168.100.151
  SETUP="-2819.423, 2082.716, 308.71, 0, 0, 33.885"
  echo "starting senseSick_LD_MRS FL -s ${SICK_IP} -q ${SETUP}"
  senseSick_LD_MRS -s ${SICK_IP} -q ${SETUP}
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
