#!/bin/bash

function component {
  if [  "$VDEMO_robot_config_loaded" = "TRUE" ]; then
        ${prefix}/bin/ArmControlRemoteServer --setMovement grasp_up
  else
          ${prefix}/bin/ArmControlRemoteServer --setMovement grasp_up
  fi        
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}


source "$VDEMO_root/vdemo_standard_component_suffix.sh"
