#!/bin/bash

title="JavaLegDetector"

function component {
    if [  "$PT_PIPELINE" = "rsb" ]; then
        ${prefix}/opt/legdetector/bin/JavaLegDetector -source-scope /ros4rsb/laserscan -target-scope /hri/percepts/legs
    else
        ${prefix}/opt/legdetector/bin/JavaLegDetector -s ShortTerm -source LaserData
    fi
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"