#!/bin/bash

function component {
  cd /home/itsowl/Dokumente/VEE_Umfelderkennung/murox_dev/project/tools/rsb_ws_bridge_claas
  echo "starting rsb_ws_bridge_claas"
  rsb_ws_bridge_claas
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
