#!/bin/bash

function component {
  echo "starting senseS10Terminal"
#  -h [ --help ]         Display a help message.
#  -o [ --outscope ] arg Scope for sending Nmea values
#  -p [ --port ] arg     Portnumber of ttyS<0-15> (Standardvalue: 3)
#  -b [ --bdrate ] arg   Baudrate (Standardvalue: 19200)
  senseS10Terminal -p 3 -b 115200
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
