#!/bin/bash

function component {
    xeyes
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}


source "$VDEMO_root/vdemo_standard_component_suffix.sh"
