#!/bin/bash

function component {

    if [  "$VDEMO_robot_config_loaded" = "TRUE" ]; then
        #LD_LIBRARY_PATH=${prefix}/lib:${prefix}/usr/lib:${prefix}/lib/vtk-5.6 OPEN_NI_INSTALL_PATH=${prefix} \
        ${prefix}/bin/PointCloudAnalyzer \
        -p FurnitureProcessor \
        -l ${prefix}/etc/pca/logging.properties \
        -c ${prefix}/etc/pca/pca.cfg \
        --always-publish
    else
        ${prefix}/bin/SeAM_planesim ${prefix}/etc/SeAM/sim/bonsai.xml
    fi   

}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
