#!/bin/bash

function component {
  if [  "$VDEMO_machine_config_loaded" = "TRUE" ]; then
     echo "done"
  else
     export SPREADCONFIG="${VDEMO_demoRoot}/data/spread-localhost.conf"
     export SPREADOPTS="-n localhost"
  fi
  
  echo "starting spread ${SPREADOPTS} -c $SPREADCONFIG"
  spread ${SPREADOPTS} -c $SPREADCONFIG
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    # Using -r when there is no specific need for is DARK AND EVIL
    # If Spread_Port is empty /tmp/ will be erased!
    rm -f /tmp/${SPREAD_PORT:-4803}
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
