#!/bin/bash

function component {
  echo "starting sensing PepperlFuchsOMD8000"
#   -h [ --help ]         Display a help message.
#   -o [ --outscope ] arg Scope for sending odometry values
#   -t [ --period ] arg   Update interval in ms ( 20 for maximum rate)
#   -p [ --port ] arg     Portnumber of ttyS<0-15> (Standardvalue: 0)
#   -b [ --bdrate ] arg   Baudrate (Standardvalue: 115200)
  sensePepperlFuchsOMD8000 -o / sense/PepperlFuchsOMD8000 -t 0 -p 2 -b 115200
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
