#!/bin/bash

source ${prefix}/ros/setup.bash

function component {
  if [  "$VDEMO_robot_config_loaded" = "TRUE" ]; then
       export ROS_MASTER_URI=http://$upper:11311
       DISPLAY=:0.0 roslaunch ros4xcf ros4xcf_mobile_dynamic_map.launch
  else
        DISPLAY=:0.0 roslaunch ros4xcf ros4xcf_sim_dynamic_map.launch
  fi 

}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
