#!/bin/bash

function component {

    if [  "$VDEMO_robot_config_loaded" = "TRUE" ]; then
        LD_LIBRARY_PATH=${prefix}/lib:${prefix}/lib/vtk-5.6 \
        ${prefix}/bin/PointCloudAnalyzer \
        -s pca \
        -p PlaneProcessor \
        -l ${prefix}/etc/pca/logging.properties \
        -c ${prefix}/etc/pca/pca_planes.cfg
    else
        ${prefix}/bin/SeAM_planesim ${prefix}/etc/SeAM/sim/bonsai.xml
    fi   

}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
