#!/bin/bash


function component {

    if [  "$DEBUG_MODE" = "TRUE" ]; then
        DEBUG_FLAG="--debug"
    fi

    if [  "$PT_PIPELINE" = "rsb" ]; then
        RSB_FLAG="--rsb" 
    fi
    
    # The condition a person hypothesis must fulfill before it is inserted into the scene memory. 
	# 0: At least a face OR a leg OR a body percept must be present for the person (default). 
	# 1: At least a leg percept must be present for the person. 
	# 2: At least a face percept must be present for the person. 
	# 3: At least a face AND a leg percept must be present for the person.
	# 4: At least a body percept must be present for the person. 
	# 5: At least a body AND a leg percept must be present for the person. 
	# 6: At least a face AND a leg AND a body percept must be present for the person.
	CONDITION=1
    
    ${prefix}/bin/ObjectBuilderAM -i ${CONDITION} ${RSB_FLAG} ${DEBUG_FLAG}
    
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"