#!/bin/bash

function component {
    # Always load with camera until we have a better video
    if $VDEMO_simulation; then 
	    ${prefix}/bin/FaceRecSim
    else
        ${prefix}/bin/FaceRec -c ${prefix}/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml -d ${prefix}/share/FaceRec -o rsb:/faces -r fisherfaces -u 0.6 --internalDet 0

    fi 
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
