#!/bin/bash

# common parameters


function component {
    MODULE="${BIRON_icewingDir}/icewing"
    DC_CONTROL_OPTIONS="-rc ${VDEMO_demoRoot}/data/icewing/settingsObjectDetectionKinect -sp ${prefix}/share/images/DSLR/*.jpg"
    CLASSES=""
    for ARG in `cat ${prefix}/share/objectModels/coldClasses.txt`
    do
	CLASSES="${prefix}/share/objectModels/$ARG.png;$CLASSES"
    done
	${MODULE} ${DC_CONTROL_OPTIONS} \
	-l ${prefix}/lib/iceWing/libXcfChainSwitch.so \
	-a XcfChainSwitch1 "-s OdcChainSwitchServer -f ${VDEMO_demoRoot}/data/chainSwitchConfigKinect5DOdc.xml" \
	-l ${prefix}/lib/iceWing/libXCFExport.so \
	-a XCFExport1 "-x odcObject -i export_bb_in" \
	-l ${prefix}/lib/iceWing/libXCFExport.so \
	-a XCFExport2 "-x odcObject3D -i CroppedXYZ" \
	-l ${prefix}/lib/iceWing/libiw_cold2.so \
	-a iw_cold21 "-m ${CLASSES} -i image" \
	-l ${prefix}/lib/iceWing/libPMKSVM.so \
	-a PMKSVM1 "-d ${prefix}/share/objectModels -c ${prefix}/share/objectModels/101_clusters -i image -b pmk_bb_in --no-hypotheses"
}

function clean_component {
    true
}

function on_start {
    true
}

function on_check {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
