#!/bin/bash

source ${prefix}/ros/setup.bash

function component {
	echo "Starting waving_detection with ROS_MASTER_URI $ROS_MASTER_URI"
	DISPLAY=:0.0 roslaunch wave_detection wave_tracker.launch

#	# Hack to reset bash variables to defaults
#        command="source ${prefix}/ros/setup.bash;export ROS_MASTER_URI=${ROS_MASTER_URI};roslaunch wave_detection wave_tracker.launch"
#        echo "starting waving detection: $command"
#	xterm -e $command


}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
