uint32                        objectID 
uint32                        propertiesAvailable  # These Flags indicate what kind of Properties are available for this particular Object. Bit1: untracked Properties Bit3: tracked Properties Others: internal
uint32                        interfaceFlags 
uint32                        attributeFlags 
IbeoScala_UntrackedProperties untackedProperties 
IbeoScala_TrackedProperties   trackedProperties  
