Header  header

float64  dir              # < True track made good (degrees) */
int32    dir_t            # < Fixed text 'T' indicates that track made good is relative to true north */
float64  dec              # < Magnetic track made good */
int32    dec_m            # < Fixed text 'M' */
float64  spn              # < Ground speed, knots */
int32    spn_n            # < Fixed text 'N' indicates that speed over ground is in knots */
float64  spk              # < Ground speed, kilometers per hour */
int32    spk_k            # < Fixed text 'K' indicates that speed over ground is in kilometers/hour */

