int32 CENTEROFGRAVITY = 1   # Center of gravity
int32 FRONTLEFT       = 2   # Front/Left
int32 FRONTRIGHT      = 3   # Front/Right
int32 REARRIGHT       = 4   # Rear/Right
int32 REARLEFT        = 5   # Rear/Left
int32 FRONTCENTER     = 6   # Front/Center
int32 RIGHTCENTER     = 7   # Right/Center
int32 REARCENTER      = 8   # Rear/Center
int32 LEFTCENTER      = 9   # Left/Center
int32 OBJECTCENTER    = 10  # Object Center
int32 UNKNOWN         = 11  # unknown

